name: BUILD_AND_PUSH

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run:
        cd base
        docker build -t ${GITHUB_REPOSITORY}:${GITHUB_REF:11} .
    - name: Upload Docker Image
      env:
        IMAGE_NAME: getshifter-actions-base
        my_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker tag ${GITHUB_REPOSITORY}:${GITHUB_REF:11} docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${GITHUB_REF:11}
        docker login docker.pkg.github.com -u ${GITHUB_ACTOR} -p ${my_token}
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${GITHUB_REF:11}
